exports.WEB_SOCKET_READY_STATE_CHANGE = 'WEB_SOCKET_READT_STATE_CHANGE'

exports.REQUEST_CS_SUCCESS = 'REQUEST_CS_SUCCESS'

exports.PUSH_CHAT_LOG = 'PUSH_CHAT_LOG'

exports.RECEIVE_MSG = 'RECEIVE_MSG'

exports.CUSTOMER_SEND_MSG = 'CUSTOMER_SEND_MSG'

exports.CUSTOMER_SEND_MSG_SUCCESS = 'CUSTOMER_SEND_MSG_SUCCESS'

exports.MSG_GET_READ = 'MSG_GET_READ'

exports.GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS'

exports.CUSTOMER_WS_LOG_IN = 'CUSTOMER_WS_LOG_IN'

exports.CUSTOMER_WS_LOG_IN_SUCCESS = 'CUSTOMER_WS_LOG_IN_SUCCESS'

exports.CUSTOMER_REQUEST_CS = 'CUSTOMER_REQUEST_CS'

exports.CUSTOMER_CANCEL_REQUEST_CS = 'CUSTOMER_CANCEL_REQUEST_CS'

exports.CS_CHAT_END = 'CS_CHAT_END'

exports.CUSTOMER_QUIT_CHAT = 'CUSTOMER_QUIT_CHAT'

exports.MSG_FROM_OWN = 'MSG_FROM_OWN'

exports.CHAT_ALREADY_EXISTS = 'CHAT_ALREADY_EXISTS'


//Staff
exports.STAFF_SET_INFO = 'STAFF_SET_INFO'

exports.STAFF_WS_LOG_IN = 'STAFF_WS_LOG_IN'

exports.STAFF_ACCEPT_CUSTOMER = 'STAFF_ACCEPT_CUSTOMER'

exports.STAFF_CHATTING_WITH = 'STAFF_CHATTING_WITH'

exports.STAFF_SEND_MSG = 'STAFF_SEND_MSG'

exports.STAFF_SEND_MSG_SUCCESS = 'STAFF_SEND_MSG_SUCCESS'

exports.STAFF_CLOSE_CHAT = 'STAFF_CLOSE_CHAT'

exports.STAFF_CLOSE_CHAT_SUCCESS = 'STAFF_CLOSE_CHAT_SUCCESS'


exports.READ_MSG = 'READ_MSG'

exports.FILE_UPLOAD_HEAD = 'FILE_UPLOAD_HEAD'

exports.FILE_UPLOAD_FRAGMENT = 'FILE_UPLOAD_FRAGMENT'

exports.FILE_UPLOAD_END = 'FILE_UPLOAD_END'

exports.CS_WAITING_COUNT = 'CS_WAITING_COUNT'

exports.MsgType = { TEXT: 1, IMAGE: 2 }