
export const WEB_SOCKET_READY_STATE_CHANGE = 'WEB_SOCKET_READT_STATE_CHANGE'

export const REQUEST_CS_SUCCESS = 'REQUEST_CS_SUCCESS'

export const PUSH_CHAT_LOG = 'PUSH_CHAT_LOG'

export const RECEIVE_MSG = 'RECEIVE_MSG'

export const CUSTOMER_SEND_MSG = 'CUSTOMER_SEND_MSG'

export const CUSTOMER_SEND_MSG_SUCCESS = 'CUSTOMER_SEND_MSG_SUCCESS'

export const MSG_GET_READ = 'MSG_GET_READ'

export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS'

export const CUSTOMER_WS_LOG_IN = 'CUSTOMER_WS_LOG_IN'

export const CUSTOMER_WS_LOG_IN_SUCCESS = 'CUSTOMER_WS_LOG_IN_SUCCESS'

export const CUSTOMER_REQUEST_CS = 'CUSTOMER_REQUEST_CS'

export const CUSTOMER_CANCEL_REQUEST_CS = 'CUSTOMER_CANCEL_REQUEST_CS'

export const CS_CHAT_END = 'CS_CHAT_END'

export const CUSTOMER_QUIT_CHAT = 'CUSTOMER_QUIT_CHAT'

export const MSG_FROM_OWN = 'MSG_FROM_OWN'

export const CHAT_ALREADY_EXISTS = 'CHAT_ALREADY_EXISTS'


export const STAFF_SET_INFO = 'STAFF_SET_INFO'

export const STAFF_WS_LOG_IN = 'STAFF_WS_LOG_IN'

export const STAFF_ACCEPT_CUSTOMER = 'STAFF_ACCEPT_CUSTOMER'

export const STAFF_CHATTING_WITH = 'STAFF_CHATTING_WITH'

export const STAFF_SEND_MSG = 'STAFF_SEND_MSG'

export const STAFF_SEND_MSG_SUCCESS = 'STAFF_SEND_MSG_SUCCESS'

export const STAFF_CLOSE_CHAT = 'STAFF_CLOSE_CHAT'

export const STAFF_CLOSE_CHAT_SUCCESS = 'STAFF_CLOSE_CHAT_SUCCESS'

export const READ_MSG = 'READ_MSG'

export const FILE_UPLOAD_HEAD = 'FILE_UPLOAD_HEAD'

export const FILE_UPLOAD_FRAGMENT = 'FILE_UPLOAD_FRAGMENT'

export const FILE_UPLOAD_END = 'FILE_UPLOAD_END'

export const CS_WAITING_COUNT = 'CS_WAITING_COUNT'

export const MsgStatus = { SENDING: 0, UNREAD: 1, READ: 2, WRONG: 3 };

export const MsgType = { TEXT: 1, IMAGE: 2 }